version: '3.5'

networks:
 metrics-network:
    name: metrics-network

services:
 metrics:
    build: ./development
    image: metrics_service:dev
    expose:
      - 80
    networks:
      - metrics-network
    restart: always
    volumes:
      - /home/diagro/service_metrics:/diagro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metrics_service.entrypoints=websecure"
      - "traefik.http.routers.metrics_service.rule=Host(`metrics.diagro.dev`)"
      - "traefik.http.routers.metrics_service.tls=true"
      - "traefik.http.routers.metrics_service.tls.certresolver=production"
      - "traefik.docker.network=metrics-network"
